import { generateManifest, generateHeadSnippet } from './favicon-manifest';
import type { FaviconSettings } from '../models/favicon-settings';
import { DEFAULT_FAVICON_SETTINGS } from '../models/favicon-settings';

const SAMPLE_SETTINGS: FaviconSettings = {
  backgroundColor: '#ff0000',
  appName: 'Test App',
  appShortName: 'Test',
};

describe('generateManifest', () => {
  it('should produce valid JSON structure', () => {
    const manifest = generateManifest(SAMPLE_SETTINGS);
    const json = JSON.stringify(manifest);

    expect(() => JSON.parse(json)).not.toThrow();
    expect(manifest.name).toBe('Test App');
    expect(manifest.short_name).toBe('Test');
    expect(manifest.theme_color).toBe('#ff0000');
    expect(manifest.background_color).toBe('#ff0000');
    expect(manifest.display).toBe('standalone');
  });

  it('should include android-chrome icons in manifest', () => {
    const manifest = generateManifest(SAMPLE_SETTINGS);

    expect(manifest.icons.length).toBe(2);

    const icon192 = manifest.icons.find((i) => i.sizes === '192x192');
    expect(icon192).toBeDefined();
    expect(icon192!.src).toBe('/android-chrome-192x192.png');
    expect(icon192!.type).toBe('image/png');

    const icon512 = manifest.icons.find((i) => i.sizes === '512x512');
    expect(icon512).toBeDefined();
    expect(icon512!.src).toBe('/android-chrome-512x512.png');
    expect(icon512!.type).toBe('image/png');
  });

  it('should use settings values', () => {
    const customSettings: FaviconSettings = {
      backgroundColor: '#00ff00',
      appName: 'Custom App',
      appShortName: 'Custom',
    };

    const manifest = generateManifest(customSettings);

    expect(manifest.name).toBe('Custom App');
    expect(manifest.short_name).toBe('Custom');
    expect(manifest.theme_color).toBe('#00ff00');
    expect(manifest.background_color).toBe('#00ff00');
  });
});

describe('generateHeadSnippet', () => {
  it('should include favicon ICO link', () => {
    const snippet = generateHeadSnippet(SAMPLE_SETTINGS);
    expect(snippet).toContain('href="/favicon.ico"');
  });

  it('should include all PNG favicon sizes', () => {
    const snippet = generateHeadSnippet(SAMPLE_SETTINGS);

    expect(snippet).toContain('favicon-16x16.png');
    expect(snippet).toContain('favicon-32x32.png');
    expect(snippet).toContain('favicon-48x48.png');
    expect(snippet).toContain('apple-touch-icon.png');
    expect(snippet).toContain('android-chrome-192x192.png');
    expect(snippet).toContain('android-chrome-512x512.png');
  });

  it('should include web manifest link', () => {
    const snippet = generateHeadSnippet(SAMPLE_SETTINGS);
    expect(snippet).toContain('href="/site.webmanifest"');
  });

  it('should include theme-color meta tag with settings background', () => {
    const snippet = generateHeadSnippet(SAMPLE_SETTINGS);
    expect(snippet).toContain('content="#ff0000"');
  });

  it('should include apple-mobile-web-app meta tags', () => {
    const snippet = generateHeadSnippet(SAMPLE_SETTINGS);
    expect(snippet).toContain('apple-mobile-web-app-capable');
    expect(snippet).toContain('apple-mobile-web-app-title');
    expect(snippet).toContain('content="Test"');
  });

  it('should update theme color when settings change', () => {
    const snippet = generateHeadSnippet({ ...SAMPLE_SETTINGS, backgroundColor: '#0000ff' });
    expect(snippet).toContain('content="#0000ff"');
  });

  it('should use default settings', () => {
    const snippet = generateHeadSnippet(DEFAULT_FAVICON_SETTINGS);
    expect(snippet).toContain('content="#ffffff"');
    expect(snippet).toContain('content="App"');
  });

  it('should contain the generation comment', () => {
    const snippet = generateHeadSnippet(SAMPLE_SETTINGS);
    expect(snippet).toContain('Generated by OpticPress Favicon Tool');
  });
});
