import type { FaviconSettings, FaviconManifest } from '../models/favicon-settings';
import {
  FAVICON_ICO_FILENAME,
  FAVICON_PNG_BY_SIZE,
  APPLE_TOUCH_ICON_FILENAME,
  ANDROID_CHROME_BY_SIZE,
  APPLE_TOUCH_ICON_SIZE,
  FAVICON_PNG_SIZES,
  ANDROID_CHROME_SIZES,
} from '../models/favicon-settings';

export function generateManifest(settings: FaviconSettings): FaviconManifest {
  return {
    name: settings.appName,
    short_name: settings.appShortName,
    icons: [
      {
        src: `/${ANDROID_CHROME_BY_SIZE[192]}`,
        sizes: '192x192',
        type: 'image/png',
      },
      {
        src: `/${ANDROID_CHROME_BY_SIZE[512]}`,
        sizes: '512x512',
        type: 'image/png',
      },
    ],
    theme_color: settings.backgroundColor,
    background_color: settings.backgroundColor,
    display: 'standalone',
  };
}

export function generateManifestBlob(settings: FaviconSettings): Blob {
  const json = JSON.stringify(generateManifest(settings), null, 2);
  return new Blob([json], { type: 'application/manifest+json' });
}

export function generateHeadSnippet(settings: FaviconSettings): string {
  const lines: string[] = [
    `<!-- Generated by OpticPress Favicon Tool -->`,
    ``,
    `<!-- Favicon ICO -->`,
    `<link rel="icon" type="image/x-icon" href="/${FAVICON_ICO_FILENAME}">`,
    ``,
    `<!-- Favicon PNGs -->`,
  ];

  for (const size of FAVICON_PNG_SIZES) {
    const filename = FAVICON_PNG_BY_SIZE[size];
    lines.push(
      `<link rel="icon" type="image/png" sizes="${size}x${size}" href="/${filename}">`,
    );
  }

  for (const size of ANDROID_CHROME_SIZES) {
    const filename = ANDROID_CHROME_BY_SIZE[size];
    lines.push(
      `<link rel="icon" type="image/png" sizes="${size}x${size}" href="/${filename}">`,
    );
  }

  lines.push(
    ``,
    `<!-- Apple Touch Icon -->`,
    `<link rel="apple-touch-icon" sizes="${APPLE_TOUCH_ICON_SIZE}x${APPLE_TOUCH_ICON_SIZE}" href="/${APPLE_TOUCH_ICON_FILENAME}">`,
    ``,
    `<!-- Web App Manifest -->`,
    `<link rel="manifest" href="/site.webmanifest">`,
    ``,
    `<!-- Theme & Meta -->`,
    `<meta name="theme-color" content="${settings.backgroundColor}">`,
    `<meta name="apple-mobile-web-app-capable" content="yes">`,
    `<meta name="apple-mobile-web-app-title" content="${settings.appShortName}">`,
  );

  return lines.join('\n');
}

export function generateHeadSnippetBlob(settings: FaviconSettings): Blob {
  const html = generateHeadSnippet(settings);
  return new Blob([html], { type: 'text/html' });
}
